### ISSUE TITLE
Class 'LaravelDm8\Dm8\Schema\OracleBlueprint' not found

### ISSUE THREAD

**Issue by lddtime** [maxlcoder/laravel-dm8#2]
执行迁移命令报错

![image](https://github.com/maxlcoder/laravel-dm8/assets/19882218/9a7ffc09-0c44-4650-bc17-de59e422aa45)

**Comment by maxlcoder** [comment]
> 执行迁移命令报错
> 
> ![image](https://private-user-images.githubusercontent.com/19882218/329206884-9a7ffc09-0c44-4650-bc17-de59e422aa45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODIzNTcsIm5iZiI6MTcxNjk4MjA1NywicGF0aCI6Ii8xOTg4MjIxOC8zMjkyMDY4ODQtOWE3ZmZjMDktMGM0NC00NjUwLWJjMTctZGU1OWU0MjJhYTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMjczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NmRjYmQ2M2VjNzYxMDFkMzc3MTVlNGNhNzc0ZjRlNmQyNzE0MmZmNGUzNjRiOGY0NWEyMTNjM2Y3M2I2ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-2iHYKYpMj-gpVm6v7RmZoy3oMshZ273nQwL4XTm4hE

用最新版本的，应该修复了这个问题
